### ISSUE TITLE
prezzo filtri 

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#13]
![schermata 2015-07-29 alle 16 38 26](https://cloud.githubusercontent.com/assets/13416234/8960661/54e8dabe-3611-11e5-945a-a7a65b1d4e1d.png)

**Comment by Anto-estroverso** [comment]
Effettivamente è un problema difficile da gestire..
Aggiungeremo un check "trattativa riservata" di default già attivo (sotto il filtro "solo in promozione") in modo che l'utente possa decidere se escluderle o meno dalla ricerca.

**Comment by davide-cm** [comment]
Eventualemtne sui prodotti con prezzo cicli mattio 0,00€ 
possiamo aggiungere un "icona/nota" trattativa riservata
