### ISSUE TITLE
area depositi

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#14]
non mi ricordo dove la trovo sul pannello di controllo lato PUBBLICO

**Comment by Anto-estroverso** [comment]
Nel profilo utente (inseriremo un banner più visibile anche in home page).

**Comment by davide-cm** [comment]
grazie va bene

forse giovanni lo immaginava come "banner" in home page

ma adesso è facile spiegare dove deve andare a fare il deposito
basta dire vai sul tuo profilo

ciao
