### ISSUE TITLE
titolo prodotto 

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#19]
![schermata 2015-07-29 alle 15 00 33](https://cloud.githubusercontent.com/assets/13416234/8962422/ce2d7066-361a-11e5-9492-3fc0e8a42216.png)

**Comment by Anto-estroverso** [comment]
Noi ti proponiamo di fare esattamente il contrario :)
Un'importante regola di usabilità sui siti è non scrivere tutto in maiuscolo per migliorare la chiarezza dei contenuti. Il maiuscolo deve essere invece utilizzato correttamente, per i nomi propri, le sigle dei prodotti e (con molta parsimonia) per enfatizzare una singola parola.

**Comment by davide-cm** [comment]
ok

es. nome prodotto di due prodotti

BMC bici corsa rossa   >>>> lo vedo >>>>>>> bmc bici corsa rossa o BMC BICI CORSA ROSSA
BMC bici corsa rossa   >>>> lo vedo >>>>>>> BMC bici corsa rossa

?

**Comment by davide-cm** [comment]
Ok 
chiudiamo

sarà la persona che carica a titoli  i titoli (maiuscolo e minuscolo)
