### ISSUE TITLE
informazioni (mail )

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#22]
![schermata 2015-07-29 alle 15 41 40](https://cloud.githubusercontent.com/assets/13416234/8962555/7f0d84de-361b-11e5-9df1-5fa9b6911c11.png)

**Comment by Anto-estroverso** [comment]
Ok, il link lo togliamo e al posto potrai inserire una email per l'esperto.

**Comment by davide-cm** [comment]
grazie
chiudo
