### ISSUE TITLE
categoria

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#44]
nella sezione categoria mette in ordine alfabetico oppure a random?

http://5.196.6.10/admin/list-categorie.php

es. settore componenti (C) > viene prima di settore accessori (A)

ciao

**Comment by giosh** [comment]
L'elenco è in ordine alfabetico, ordinato in questo modo:

-- ordine alfabetico settori
---- ordine alfabetico categorie

In questo modo tutti i settori sono ordinati insieme e, all'interno dell'ordine alfabetico dei settori, le categorie sono in ordine alfabetico
