### ISSUE TITLE
categorie "espanse"

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#6]
ci piacerebbe, se possibile, che fossero maggiormente espanse le sottocategorie
così rimane tutto visivo a primo impatto 
![2015-07-29 alle 09 22 04](https://cloud.githubusercontent.com/assets/13416234/8952076/fc3469de-35d3-11e5-8b0c-d3fdea383525.png)

**Comment by Anto-estroverso** [comment]
Aggiungere tooltip con elenco sottocategorie onover
