### ISSUE TITLE
login amministrazione

### ISSUE THREAD

**Issue by davide-cm** [ciclimattio/ciclimattio-issue#8]
secondo me sarebbe carino che ogni dipendente del negozio potesse entrare con un proprio nome utente e psw

magari ad ogni utente corrisponde un livello di navigabilità dell'area riservata differente 

es. davide@ciclimattio + psw...

**Comment by Anto-estroverso** [comment]
Inviaci una lista degli utenti che vorresti creare.
Per ora non è possibile definire ruoli, ma è una funzione che possiamo aggiungere in futuro.

**Comment by davide-cm** [comment]
ciao
per ora ritieni questo punto sospeso. perché abbiamo differenti visioni in ufficio. 
mettilo tra i risolti.
